### ISSUE TITLE
"This application can't be launch directly."

### ISSUE THREAD

**Issue by 0xelion** [LedgerHQ/android-u2f-bridge#3]
When i start the application on my android, it close instantly and say :

"This application can't be launch directly."

**Comment by cosmojg** [comment]
That's because it can't be launched directly. It's intended to be the interface between web apps like MyEtherWallet and your Ledger device.

**Comment by 0xelion** [comment]
And how can you connect the Ledger Nano S and MEW then?

**Comment by cosmojg** [comment]
Navigate to MyEtherWallet.com in Chrome, tap "Send Ether & Tokens," tap "Ledger Nano S," and finally tap "Connect to Ledger Nano S." Make sure your Ledger device is plugged in. The app will launch, and things should go as they usually do.

**Comment by btchip** [comment]
Has been answered, so closing.
